### PR TITLE
[keycloak-gatekeeper] Make the chart's apiVersion compatible with Helm v2

### PR DESCRIPTION
**Pull request by legal90**
Hi @gabibbo97 ,

Thank you for your `keycloak-gatekeeper` chart!  Can you please keep it compatible with Helm 2 for some time? That will help users like me to use the latest version of the chart and continue working on the Helm v3 migration.

This PR shows that the only incompatible thing there is the `type` field and `apiVersion`. All templates are working fine with both Helm 2 and 3

Thank you!

### CODE REVIEW

**Comment by gabibbo97** [comment]
Hi, I do think that this is a breaking change, you should upgrade the major version number

**Comment by legal90** [comment]
@gabibbo97 Do you mean bumping the chart version `2.2.0` -> `3.0.0`? I can do that in this PullRequest, no problem

**Comment by legal90** [comment]
Done 👍

**Comment by gabibbo97** [comment]
Exactly what I meant, merged

**Pull request merged**
